name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame pyinstaller pyautogui pillow pyscreeze pymsgbox mouseinfo pygetwindow


      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed --add-data "assets;assets" \
          --hidden-import=pyautogui --hidden-import=pyscreeze --hidden-import=pymsgbox \
          --hidden-import=mouseinfo --hidden-import=pygetwindow game.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: game-windows
          path: dist/*.exe
